[[override]]
  name = "github.com/bvandewalle/go-ipset"
  revision = "0ee897a6d8bc6095299e9c03293ece091ef871de"

[[constraint]]
  name = "github.com/aporeto-inc/netlink-go"
  branch = "context"

[[constraint]]
  name = "github.com/aporeto-inc/tg"
  version = "2.x"
